### ISSUE TITLE
API and console servers should have their own directories

### ISSUE THREAD

**Issue by rajkissu** [olindata/puppet-opstheatre#1]
Right now, this puppet module attempts to clone both opstheatre and opstheatre-frontend modules to the same directory. This should be changed to cater for different directories for both servers.

**Comment by choonming** [comment]
You can specify the directory you want the class parameters.

class { 'opstheatre::api': docroot => '/var/www/opstheatre/api' }
class { 'opstheatre::console: docroot => '/var/www/opstheatre/console' }

**Comment by rajkissu** [comment]
That works, but wouldn't it make sense to have it added in params.pp? So it'll work out of the box without specifying parameters. Then in the event they do want to customize it, they can do so accordingly.

**Comment by choonming** [comment]
There is a parameter for docroot on params.pp. It is built with the assumption that both the api and console will be on different servers. I'll customize the parameters a bit
